# Generated by Django 5.2.5 on 2025-09-08 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trackers", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="trackers",
            new_name="tracker",
        ),
        migrations.AlterField(
            model_name="trackerimage",
            name="tracker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="trackers.tracker",
            ),
        ),
    ]
