# Generated by Django 5.2.5 on 2025-09-01 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trackers", "0002_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="trackers",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="trackers.tracker"
            ),
        ),
    ]
