# Generated by Django 5.2.5 on 2025-09-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trackers", "0002_rename_trackers_comment_tracker_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracker",
            name="tracker_id",
            field=models.CharField(
                blank=True, editable=False, max_length=20, null=True, unique=True
            ),
        ),
    ]
