# Generated by Django 5.2.5 on 2025-09-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trackers", "0005_auto_20250908_2249"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tracker",
            options={"ordering": ["-date"]},
        ),
        migrations.AddField(
            model_name="comment",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="comment_images/"),
        ),
    ]
